# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8236f6f02bb67d041b20a69e351e2f9c2c733dd7b906366e4beb615a46ce68859c88de7908cfde6f330b9620e789ae2e8b0cecef63cddc9524d2727bd48d061f

test:
  secret_key_base: 8d185b42bf463618500732d0f4efb56ce79590e0514abf8c621014120fbc4221ce10dd515698c00486ff52d8f30c31c1dc5a88503930e6b8489aafb86a03b5e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
